using SharpDemangler.Microsoft;
using System.Diagnostics;

namespace DLLToHeader;

public static class FileGenerator
{
    public static bool GenerateDefFile(string deffile, List<SymbolNode> asts, bool use_oridinal = false)
    {
        if (!string.IsNullOrEmpty(deffile))
        {
            using var writer = new StreamWriter(deffile);
            writer.WriteLine($"; Generated by DLLToHeader");

            writer.WriteLine("LIBRARY \"" + Path.GetFileNameWithoutExtension(deffile) + "\"");
            writer.WriteLine("EXPORTS");
            // write exports
            foreach (var ast in asts)
            {
                if (ast.Kind != NodeKind.Identifier)
                {
                    var text = ast.ToString();
                    writer.WriteLine(";\t" + text);
                }
                writer.Write("\t" + ast.Text);
                if (use_oridinal)
                {
                    writer.Write($" @{ast.Ordinal}");
                }
                writer.WriteLine();
            }
            return true;
        }
        return false;
    }
    public static void GenerateHeaderFile(
        Dictionary<NodeArrayNode, Dictionary<NodeArrayNode, List<SymbolNode>>> namespace_classes,
        List<NodeArrayNode> namespaces,
        Dictionary<NodeArrayNode, NodeArrayNode> class_namespaces,
        Dictionary<NodeArrayNode, SymbolNode> global_functions,
        Dictionary<NodeArrayNode, HashSet<QualifiedNameNode>> class_bases,
        List<SymbolNode> plains,
        string hdrfile, string libfile)
    {
        using var writer = new StreamWriter(hdrfile);
        writer.WriteLine("#pragma once");
        writer.WriteLine("#define DLLIMPORT __declspec(dllimport)");
        writer.WriteLine($"#pragma comment(lib,\"{libfile}\")");
        writer.WriteLine();

        if (plains.Count > 0)
        {
            writer.WriteLine("extern \"C\"");
            writer.WriteLine("{");
            foreach (var ast in plains)
            {
                writer.WriteLine($"\tDLLIMPORT void {ast}();");
            }
            writer.WriteLine("}");
            writer.WriteLine();
        }
        foreach (var ns in namespace_classes)
        {
            writer.WriteLine($"namespace {QualifiedNameNode.From(ns.Key)}");
            writer.WriteLine("{");

            foreach (var ks in ns.Value)
            {
                var full = new NodeArrayNode
                {
                    Kind = NodeKind.NodeArray,
                    Nodes = [.. ns.Key.Nodes, .. ks.Key.Nodes]
                };
                if (!global_functions.ContainsKey(full))
                {
                    writer.WriteLine($"\tclass {QualifiedNameNode.From(ks.Key)};");
                }
            }
            foreach (var cs in ns.Value)
            {
                var full = new NodeArrayNode
                {
                    Kind = NodeKind.NodeArray,
                    Nodes = [.. ns.Key.Nodes, .. cs.Key.Nodes]
                };
                if (!global_functions.ContainsKey(full))
                {
                    writer.WriteLine($"\tclass DLLIMPORT {QualifiedNameNode.From(cs.Key)}");
                    if (class_bases.TryGetValue(full, out var deps) && deps.Count > 0)
                    {
                        var any = false;
                        foreach (var dep in deps)
                        {
                            if (dep != null)
                            {
                                dep.Components = AstProcessor.TrimNamespace(dep.Components, namespaces, class_namespaces);
                                writer.Write("\t\t");
                                writer.Write(any ? ", " : ": ");
                                writer.WriteLine(dep);
                                any = true;
                            }
                        }
                    }

                    writer.WriteLine("\t{");

                    var publics = cs.Value.Where(v => v is FunctionSymbolNode fs && (fs.Signature.FunctionClass & FuncClass.Public) != 0).ToArray();
                    var protecteds = cs.Value.Where(v => v is FunctionSymbolNode fs && (fs.Signature.FunctionClass & FuncClass.Protected) != 0).ToArray();
                    var privates = cs.Value.Where(v => v is FunctionSymbolNode fs && (fs.Signature.FunctionClass & FuncClass.Private) != 0).ToArray();
                    var variables = cs.Value.Where(v => v is VariableSymbolNode vs).ToList();

                    if (variables.Count > 0)
                    {
                        var values = cs.Value.ToList();
                        var v_function_local = values.Where(v => v is VariableSymbolNode fs && (fs.sc == StorageClass.FunctionLocalStatic)).ToArray();
                        var v_publics = values.Where(v => v is VariableSymbolNode fs && (fs.sc == StorageClass.PublicStatic)).ToArray();
                        var v_protecteds = values.Where(v => v is VariableSymbolNode fs && (fs.sc == StorageClass.ProtectedStatic)).ToArray();
                        var v_privates = values.Where(v => v is VariableSymbolNode fs && (fs.sc & StorageClass.PrivateStatic) != 0 && fs.LocalFunctionName == null).ToArray();
                        if (v_publics.Length > 0)
                        {
                            writer.WriteLine("\tpublic:");
                            foreach (VariableSymbolNode vs in v_publics.Cast<VariableSymbolNode>())
                            {
                                vs.sc = StorageClass.None;
                                writer.WriteLine($"\t\tstatic {vs};");
                            }
                        }
                        if (v_protecteds.Length > 0)
                        {
                            writer.WriteLine("\tprotected:");
                            foreach (VariableSymbolNode vs in v_protecteds.Cast<VariableSymbolNode>())
                            {
                                vs.sc = StorageClass.None;
                                writer.WriteLine($"\t\tstatic {vs};");
                            }
                        }
                        if (v_privates.Length > 0)
                        {
                            writer.WriteLine("\tprivate:");
                            foreach (VariableSymbolNode vs in v_privates)
                            {
                                vs.sc = StorageClass.None;
                                writer.WriteLine($"\t\tstatic {vs};");
                            }
                        }
                        if (v_function_local.Length > 0)
                        {
                            writer.WriteLine("\t//function local static");
                            foreach (VariableSymbolNode vs in v_function_local.Cast<VariableSymbolNode>())
                            {
                                vs.sc = StorageClass.None;
                                writer.WriteLine($"\t\t//{vs};");
                            }
                        }

                    }
                    if (publics.Length > 0)
                    {
                        writer.WriteLine("\tpublic:");
                        foreach (FunctionSymbolNode ts in publics.Cast<FunctionSymbolNode>())
                        {
                            ts.Signature.FunctionClass &= ~FuncClass.Public;
                            writer.WriteLine($"\t\t{ts};");

                        }
                    }
                    if (protecteds.Length > 0)
                    {
                        writer.WriteLine("\tprotected:");
                        foreach (FunctionSymbolNode ts in protecteds.Cast<FunctionSymbolNode>())
                        {
                            ts.Signature.FunctionClass &= ~FuncClass.Protected;
                            writer.WriteLine($"\t\t{ts};");

                        }
                    }
                    if (privates.Length > 0)
                    {
                        writer.WriteLine("\tprivate:");
                        foreach (FunctionSymbolNode ts in privates.Cast<FunctionSymbolNode>())
                        {
                            ts.Signature.FunctionClass &= ~FuncClass.Private;
                            writer.WriteLine($"\t\t{ts};");

                        }
                    }

                    writer.WriteLine("\t};");
                }
                else
                {
                    //function:
                    foreach (var ts in cs.Value)
                    {
                        writer.WriteLine($"\t{ts};");
                    }
                }
                writer.WriteLine();
            }

            writer.WriteLine("}");
            writer.WriteLine();
        }

    }
    public static int GenerateLibFile(string libfile, string deffile, string machine/* = "x86"*/)
    {
        if (!string.IsNullOrEmpty(libfile) && File.Exists(deffile))
        {
            try
            {
                var p = Process.Start("link.exe", $"/LIB /DEF:{deffile} /OUT:{libfile} /MACHINE:{machine}");
                p.WaitForExit();
                return p.ExitCode;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

        }
        return -1;
    }
}