using PE_Parser;
using SharpDemangler.Microsoft;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace DLLToHeader;

public class Program
{
    //public class NameEqualtyComparer : IEqualityComparer<QualifiedNameNode>
    //{
    //    public bool Equals(QualifiedNameNode? x, QualifiedNameNode? y)
    //        => (x is null || y is null) || (x is not null && y is not null && x.Equals(y));

    //    public int GetHashCode([DisallowNull] QualifiedNameNode obj) => obj.GetHashCode();
    //}

    public static NodeArrayNode GetNamespacePart(QualifiedNameNode node) 
        => GetNamespacePart(node.Components);

    public static NodeArrayNode GetNamespacePart(NodeArrayNode node)
    {
        List<Node> results = [];
        for(int i = 0; i < node.Nodes.Length; i++)
        {
            Node n = node.Nodes[i];
            if(n is NamedIdentifierNode name)
            {
                results.Add(n);
            }

        }
        
        return new NodeArrayNode { Kind = NodeKind.NodeArray, Nodes = [.. results] };
    }
    public static NodeArrayNode GetClassPart(NodeArrayNode node)
    {
        List<Node> results = [];
        for (int i = 0; i < node.Nodes.Length; i++)
        {
            Node n = node.Nodes[i];

        }

        return new NodeArrayNode { Kind = NodeKind.NodeArray, Nodes = [.. results] };
    }

    public static int GenerateLibFile(string libfile,string deffile)
    {
        if (!string.IsNullOrEmpty(libfile) && File.Exists(deffile))
        {
            try
            {
                var p = Process.Start("link.exe", $"/LIB /DEF:{deffile} /OUT:{libfile}");
                p.WaitForExit();
                return p.ExitCode;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            
        }
        return -1;
    }
    public static bool GenerateDefFile(string deffile, List<SymbolNode> asts, bool use_oridinal  = false)
    {
        if (!string.IsNullOrEmpty(deffile))
        {
            using var writer = new StreamWriter(deffile);
            writer.WriteLine("; Generated by DLLToHeader");

            writer.WriteLine("LIBRARY \"" + Path.GetFileNameWithoutExtension(deffile) + "\"");
            writer.WriteLine("EXPORTS");
            // write exports
            foreach (var ast in asts)
            {
                if (ast.Kind != NodeKind.Identifier)
                {
                    var text = ast.ToString();
                    writer.WriteLine(";\t" + text);
                }
                writer.Write("\t" + ast.Text);
                if (use_oridinal)
                {
                    writer.Write($" @{ast.Ordinal}");
                }
                writer.WriteLine();
            }
            return true;
        }
        return false;
    }

    public static int Main(string[] args)
    {
        if (args.Length < 1)
        {
            Console.WriteLine("DLLToHeader <File.dll> [Header.h]");
        }

        var dllfile = args[0];
        var deffile = args.Length > 1 ? args[1] : Path.ChangeExtension(dllfile, ".def");
        var libfile = args.Length > 2 ? args[2] : Path.ChangeExtension(dllfile, ".lib"); 

        var header = Misc.LoadFrom(args[0]);
        var asts = new List<SymbolNode>();
        var class_bases = new Dictionary<QualifiedNameNode, HashSet<QualifiedNameNode>>();

        var namespace_classes = new Dictionary<NodeArrayNode, HashSet<SymbolNode>>();

        if (header.exportDir.exportAddr_name_t != null)
        {
            for (var i = 0; i < header.exportDir.exportAddr_name_t.Length; i++)
            {
                var demangler = new MicrosoftDemangler();
                var export = header.exportDir.exportAddr_name_t[i];
                var ast = demangler.Parse(export.names ?? "");
                if (ast != null)
                {
                    ast.Ordinal = i+1;
                    asts.Add(ast);
                    var text = demangler.Format(ast);
                    Console.WriteLine($"{text}");
                }
                else
                {
                    Console.Error.WriteLine($"Error:{export.names}");
                }
            }

            foreach (var ast in asts)
            {
                switch (ast.Kind)
                {
                    case NodeKind.VariableSymbol:
                        {
                            var @namespace = GetNamespacePart(ast.Name);
                            if (namespace_classes.TryGetValue(@namespace, out var set))
                            {
                                //null means self
                                set.Add(ast);
                            }
                            else
                            {
                                namespace_classes[@namespace] = [ast];
                            }

                        }
                        break;
                    case NodeKind.FunctionSymbol:
                        {
                            var @namespace = GetNamespacePart(ast.Name);
                            if (namespace_classes.TryGetValue(@namespace, out var set))
                            {
                                //null means self
                                set.Add(ast);
                            }
                            else
                            {
                                namespace_classes[@namespace] = [ast];
                            }
                        }
                        break;
                    case NodeKind.SpecialTableSymbol:
                        //
                        if (ast is SpecialTableSymbolNode sp)
                        {
                            if (class_bases.TryGetValue(sp.Name, out var set))
                            {
                                //null means self
                                set.Add(sp.TargetName);
                            }
                            else
                            {
                                class_bases[sp.Name] = [sp.TargetName];
                            }

                        }
                        break;
                    case NodeKind.Identifier://common function or variable
                        break;
                }
            }
        }
        //_T("//头文件,由Make Export Header自动生成\r\n")
        //            _T("#pragma once\r\n\r\n")
        //            _T("#define DLLIMPORT __declspec(dllimport)\r\n\r\n")
        //            _T("#pragma comment(lib,\"%s.lib\")\r\n\r\n"), (LPCTSTR)m_strTitle );

        if(GenerateDefFile(deffile, asts, true))
        {
            GenerateLibFile(libfile, deffile);
        }
        return 0;
    }

}